### ISSUE TITLE
コンペ最終日になるとコンペが表示されなくなるので0daysでも表示する

### ISSUE THREAD

**Issue by currypurin** [regonn/kaggle-twitter-bot#2]
@regonn 
コンペ最終日にもコンペが表示されるように、次の行を等号つきに変更したいと思いますがどうでしょうか。
問題なければプルリク送ります。

https://github.com/regonn/kaggle-twitter-bot/blob/master/main.py#L37

**Comment by regonn** [comment]
良いと思います👍
